# Generated by Django 4.0.2 on 2022-04-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=999)),
                ('description', models.CharField(max_length=999)),
                ('authors', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=999)),
                ('albums', models.CharField(max_length=999)),
                ('description', models.CharField(max_length=999)),
            ],
        ),
        migrations.DeleteModel(
            name='Janrs',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
